"""Routes for the AI assistant hint endpoint."""

# pyrefly: ignore [missing-import]
from fastapi import APIRouter, HTTPException, status

from models.ai import HintRequest, HintResponse
from services import ai_service

router = APIRouter(prefix="/ai", tags=["AI Assistant"])


@router.post("/hint", response_model=HintResponse)
async def get_code_hint(payload: HintRequest):
    """
    Accept a problem description + the user's current code and return
    a Socratic hint generated by Gemini 2.5 Flash.
    """
    if not ai_service.is_configured():
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Gemini API configuration key is missing on the server.",
        )

    try:
        return ai_service.generate_hint(payload)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Failed to communicate with the AI reasoning engine: {str(e)}",
        )
